default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dashboard_for_metricks_with_ai_development
  username: postgres
  password: 123456
  host: <%= ENV['PG_HOST'] %>

test:
  <<: *default
  database: dashboard_for_metricks_with_ai_test
  username: postgres
  password: 123456
  host: <%= ENV['PG_HOST'] %>

production:
  <<: *default
  database: dashboard_for_metricks_with_ai_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>
